from app.database import Base,engine,SessionLocal
from app.models import *
from app.auth import hash_password
Base.metadata.create_all(bind=engine); db=SessionLocal()
if db.query(User).count()==0:
 data=[("Demo Student","demo@student.com","Computer Science","Python, Machine Learning, NLP, Backend","Coding, Research","Artificial Intelligence, Machine Learning","Built an NLP chatbot using Python and machine learning","Artificial Intelligence"),("Priya Sharma","priya@example.com","Information Technology","Python, React, Machine Learning","Research, Presentation","AI, Web Development","Healthcare assistant project","Artificial Intelligence"),("Arjun Kumar","arjun@example.com","Computer Science","JavaScript, React, UI/UX, Figma","Designing, Creativity","Web Development, Design","Built responsive web apps","Web Development"),("Meena Raj","meena@example.com","Electronics","IoT, C++, Robotics","Problem Solving, Leadership","IoT, Robotics","Smart agriculture hackathon","IoT"),("Karthik V","karthik@example.com","Mechanical","CAD, Research, Python","Research, Writing","Engineering, Research","Engineering materials study","Engineering"),("Ananya Das","ananya@example.com","Computer Science","Java, SQL, Backend","Coding, Communication","Cybersecurity, Web Development","College ERP backend","Cybersecurity"),("Rahul S","rahul@example.com","Business","Marketing, Presentation, Excel","Leadership, Presentation","Business, Design","Won business pitch hackathon","Business"),("Divya P","divya@example.com","Design","Figma, UI/UX, CSS","Designing, Creativity","Design, Web Development","Designed mobile prototypes","Design"),("Vijay M","vijay@example.com","Computer Science","C, C++, Algorithms","Coding, Problem Solving","Programming, Robotics","Competitive programming","Programming"),("Sowmya G","sowmya@example.com","Biotech","Research, Biology, Data Science","Research, Writing","Research, Data Science","Bioinformatics project","Data Science")]
 for i,(n,e,d,s,t,it,ex,dom) in enumerate(data):
  u=User(name=n,email=e,password_hash=hash_password("Demo@123"),college="SRM Institute of Science and Technology",department=d,year="2",section="D"); db.add(u); db.flush(); db.add(StudentProfile(user_id=u.id,skills=s,talents=t,interests=it,experience=ex,domain=dom,availability="Weekends"))
 db.commit(); demo=db.query(User).filter_by(email="demo@student.com").first()
 projects=[("AI Healthcare Assistant","NLP assistant for healthcare guidance","Artificial Intelligence","Python, Machine Learning, NLP, React","Research, Presentation","Relevant AI or software project",4,"8 weeks"),("Smart Campus IoT","IoT monitoring for campus energy","IoT","IoT, C++, React, Research","Leadership","Hardware or IoT experience",4,"10 weeks"),("Student Startup Portal","Business and web platform","Business","React, JavaScript, UI/UX, Marketing","Presentation, Design","Startup interest",5,"6 weeks"),("Cyber Safety Tool","Student cybersecurity awareness tool","Cybersecurity","Java, SQL, Python, Research","Communication","Security experience",3,"8 weeks"),("Bio Data Explorer","Visual analytics for biology data","Data Science","Python, Data Science, Research, Figma","Writing, Presentation","Research experience",4,"12 weeks")]
 for z in projects: db.add(Project(owner_id=demo.id,title=z[0],description=z[1],domain=z[2],required_skills=z[3],required_talents=z[4],required_experience=z[5],team_size=z[6],duration=z[7],requirements="Collaborative college project"))
 db.commit()
print("Seed complete. demo@student.com / Demo@123")
